env: dev
app_project: project
app_family: family
app_name: name

api:
  port: 8088
  mode: debug
  timeout:
    read: 5s
    write: 5s
    idle: 5s

unique_id:
  type: "sonyflake" # normally, this will be set by the dx package
  start_time: "2021-01-01T01:01:01Z" # set the start time, which is part of the id
  machine_id: 1 # keep this empty on ec2 instances